name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  format:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust Nightly (2025-10-18)
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-10-18
          components: rustfmt

      - name: Check Formatting
        run: cargo +nightly-2025-10-18 fmt --check

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo Registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run Unit Tests
        run: cargo test --lib

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    services:
      clickhouse:
        image: clickhouse/clickhouse-server:25.5
        ports:
          - 9000:9000
          - 8123:8123
        env:
          CLICKHOUSE_DB: default
          CLICKHOUSE_USER: default
          CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
        options: >-
          --health-cmd "clickhouse-client --query 'SELECT 1'"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 10

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo Registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-integration-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Wait for ClickHouse
        run: |
          echo "Waiting for ClickHouse to be ready..."
          for i in {1..30}; do
            if curl -s http://localhost:8123 > /dev/null; then
              echo "ClickHouse is ready!"
              exit 0
            fi
            echo "Waiting... ($i/30)"
            sleep 2
          done
          echo "ClickHouse failed to start"
          exit 1

      - name: Run Integration Tests
        run: cargo test --test integration_test -- --ignored --nocapture
        env:
          CLICKHOUSE_HOST: localhost

      - name: Run Advanced Types Tests
        run: cargo test --test advanced_types_test -- --ignored --nocapture
        env:
          CLICKHOUSE_HOST: localhost

      - name: Run Client Advanced Tests
        run: cargo test --test client_advanced_test -- --ignored --nocapture
        env:
          CLICKHOUSE_HOST: localhost

      - name: Run Column Type Integration Tests
        run: |
          cargo test --test integration_numeric -- --ignored --nocapture
          cargo test --test integration_string -- --ignored --nocapture
          cargo test --test integration_date -- --ignored --nocapture
          cargo test --test integration_decimal -- --ignored --nocapture
          cargo test --test integration_enum -- --ignored --nocapture
          cargo test --test integration_ipv4 -- --ignored --nocapture
          cargo test --test integration_ipv6 -- --ignored --nocapture
          cargo test --test integration_uuid -- --ignored --nocapture
          cargo test --test integration_array -- --ignored --nocapture
          cargo test --test integration_nullable -- --ignored --nocapture
          cargo test --test integration_tuple -- --ignored --nocapture
          cargo test --test integration_map -- --ignored --nocapture
          cargo test --test integration_lowcardinality -- --ignored --nocapture
        env:
          CLICKHOUSE_HOST: localhost

      - name: Run Block Integration Tests - Numeric Types
        run: |
          cargo test --test integration_block_uint8 -- --ignored --nocapture
          cargo test --test integration_block_uint16 -- --ignored --nocapture
          cargo test --test integration_block_uint32 -- --ignored --nocapture
          cargo test --test integration_block_uint64 -- --ignored --nocapture
          cargo test --test integration_block_uint128 -- --ignored --nocapture
          cargo test --test integration_block_int8 -- --ignored --nocapture
          cargo test --test integration_block_int16 -- --ignored --nocapture
          cargo test --test integration_block_int32 -- --ignored --nocapture
          cargo test --test integration_block_int64 -- --ignored --nocapture
          cargo test --test integration_block_int128 -- --ignored --nocapture
          cargo test --test integration_block_float32 -- --ignored --nocapture
          cargo test --test integration_block_float64 -- --ignored --nocapture
        env:
          CLICKHOUSE_HOST: localhost

      - name: Run Block Integration Tests - String and UUID Types
        run: |
          cargo test --test integration_block_string -- --ignored --nocapture
          cargo test --test integration_block_fixedstring -- --ignored --nocapture
          cargo test --test integration_block_uuid -- --ignored --nocapture
        env:
          CLICKHOUSE_HOST: localhost

      - name: Run Block Integration Tests - Date/Time Types
        run: |
          cargo test --test integration_block_date -- --ignored --nocapture
          cargo test --test integration_block_date32 -- --ignored --nocapture
          cargo test --test integration_block_datetime -- --ignored --nocapture
          cargo test --test integration_block_datetime64 -- --ignored --nocapture
        env:
          CLICKHOUSE_HOST: localhost

      - name: Run Block Integration Tests - Other Simple Types
        run: |
          cargo test --test integration_block_ipv4 -- --ignored --nocapture
          cargo test --test integration_block_ipv6 -- --ignored --nocapture
          cargo test --test integration_block_decimal -- --ignored --nocapture
          cargo test --test integration_block_enum8 -- --ignored --nocapture
          cargo test --test integration_block_enum16 -- --ignored --nocapture
          cargo test --test integration_block_nothing -- --ignored --nocapture
        env:
          CLICKHOUSE_HOST: localhost

      - name: Run Block Integration Tests - Array Types
        run: |
          cargo test --test integration_block_array_float32 -- --ignored --nocapture
          cargo test --test integration_block_array_float64 -- --ignored --nocapture
          cargo test --test integration_block_array_string -- --ignored --nocapture
          cargo test --test integration_block_array_int32 -- --ignored --nocapture
          cargo test --test integration_block_array_int64 -- --ignored --nocapture
          cargo test --test integration_block_array_date -- --ignored --nocapture
          cargo test --test integration_block_array_date32 -- --ignored --nocapture
          cargo test --test integration_block_array_datetime -- --ignored --nocapture
          cargo test --test integration_block_array_datetime64 -- --ignored --nocapture
          cargo test --test integration_block_array_lowcardinality_string -- --ignored --nocapture
          cargo test --test integration_block_array_decimal -- --ignored --nocapture
        env:
          CLICKHOUSE_HOST: localhost

      - name: Run Block Integration Tests - Tuple Types
        run: |
          cargo test --test integration_block_tuple_float32_float64 -- --ignored --nocapture
          cargo test --test integration_block_tuple_int32_int64 -- --ignored --nocapture
          cargo test --test integration_block_tuple_string_int64 -- --ignored --nocapture
          cargo test --test integration_block_tuple_string_int64_array_string -- --ignored --nocapture
        env:
          CLICKHOUSE_HOST: localhost

      - name: Run Block Integration Tests - Map Types
        run: |
          cargo test --test integration_block_map_int8_string -- --ignored --nocapture
          cargo test --test integration_block_map_string_array_array_int8 -- --ignored --nocapture
          cargo test --test integration_block_map_uuid_nullable_string -- --ignored --nocapture
          cargo test --test integration_block_map_uuid_nullable_lowcardinality_string -- --ignored --nocapture
        env:
          CLICKHOUSE_HOST: localhost

      - name: Run Block Integration Tests - Nullable Types
        run: |
          cargo test --test integration_block_nullable_string -- --ignored --nocapture
          cargo test --test integration_block_nullable_ipv6 -- --ignored --nocapture
          cargo test --test integration_block_nullable_uuid -- --ignored --nocapture
          cargo test --test integration_block_nullable_int64 -- --ignored --nocapture
        env:
          CLICKHOUSE_HOST: localhost

      - name: Run Block Integration Tests - LowCardinality Types
        run: |
          cargo test --test integration_block_lowcardinality_string -- --ignored --nocapture
          cargo test --test integration_block_lowcardinality_int64 -- --ignored --nocapture
          cargo test --test integration_block_lowcardinality_uuid -- --ignored --nocapture
        env:
          CLICKHOUSE_HOST: localhost

      - name: Run Other Integration Tests
        run: |
          cargo test --test block_tests -- --ignored --nocapture
          cargo test --test client_callbacks_test -- --ignored --nocapture
          cargo test --test client_feature_tests -- --ignored --nocapture
          cargo test --test column_name_edge_cases_test -- --ignored --nocapture
          cargo test --test column_tests -- --ignored --nocapture
          cargo test --test create_column_tests -- --ignored --nocapture
          cargo test --test date_nothing_column_tests -- --ignored --nocapture
          cargo test --test edge_cases_test -- --ignored --nocapture
          cargo test --test error_handling_test -- --ignored --nocapture
          cargo test --test map_lowcard_geo_tests -- --ignored --nocapture
          cargo test --test nested_complex_types_test -- --ignored --nocapture
          cargo test --test query_features_test -- --ignored --nocapture
          cargo test --test specialized_column_tests -- --ignored --nocapture
          cargo test --test type_methods_tests -- --ignored --nocapture
        env:
          CLICKHOUSE_HOST: localhost

  build:
    name: Build (Release)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo Registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build Release
        run: cargo build --release

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Cache Cargo Registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-clippy-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run Clippy
        run: cargo clippy -- -D warnings
